package vista;

import javax.swing.JOptionPane;
import modelador.Vuelo;
import controlador.ControladorColaVuelo;
import static java.awt.Frame.ICONIFIED;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Toshiba
 */
public class AgregarVueloPresidenteJPanel extends javax.swing.JPanel {

    public Principal principal;
    public ControladorColaVuelo controladorColaVuelo;

    /**
     * Creates new form AgregarVueloPresidenteJPanel
     */
    public AgregarVueloPresidenteJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jTextFieldIDVuelo = new javax.swing.JTextField();
        jTextFieldFechaSalida = new javax.swing.JTextField();
        jTextFieldCiudadLlegada = new javax.swing.JTextField();
        jTextFieldHoraRegreso = new javax.swing.JTextField();
        jTextFieldNumeroPasajeros = new javax.swing.JTextField();
        jTextFieldCiudadOrigen = new javax.swing.JTextField();
        jTextFieldHoraSalida = new javax.swing.JTextField();
        jTextFieldFechaRegreso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEstadoVuelo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabelVuelosEnEspera = new javax.swing.JLabel();
        jButton1EliminarUltimo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jLabelTituloAregarAvion = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jButtonAgregarNuevoCliente = new javax.swing.JButton();
        jButtonVolver2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(144, 202, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldIDVuelo.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldIDVuelo.setBorder(null);
        jTextFieldIDVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDVueloActionPerformed(evt);
            }
        });
        add(jTextFieldIDVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 96, 329, -1));

        jTextFieldFechaSalida.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldFechaSalida.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldFechaSalida.setBorder(null);
        add(jTextFieldFechaSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 156, 329, -1));

        jTextFieldCiudadLlegada.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCiudadLlegada.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldCiudadLlegada.setBorder(null);
        add(jTextFieldCiudadLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 456, 329, -1));

        jTextFieldHoraRegreso.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldHoraRegreso.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldHoraRegreso.setBorder(null);
        add(jTextFieldHoraRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 336, 329, -1));

        jTextFieldNumeroPasajeros.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldNumeroPasajeros.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldNumeroPasajeros.setBorder(null);
        add(jTextFieldNumeroPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 516, 329, -1));

        jTextFieldCiudadOrigen.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCiudadOrigen.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldCiudadOrigen.setBorder(null);
        add(jTextFieldCiudadOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 396, 329, -1));

        jTextFieldHoraSalida.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldHoraSalida.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldHoraSalida.setBorder(null);
        jTextFieldHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraSalidaActionPerformed(evt);
            }
        });
        add(jTextFieldHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 276, 329, -1));

        jTextFieldFechaRegreso.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldFechaRegreso.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldFechaRegreso.setBorder(null);
        add(jTextFieldFechaRegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 216, 329, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID vuelo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 96, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Fecha de salida");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 156, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha de regreso");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 216, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Ciudad origen");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 396, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Hora regreso");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 336, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Hora ida");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 276, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Numero de pasajeros");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 516, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Ciudad de llegada");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 456, -1, -1));

        jTextFieldEstadoVuelo.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldEstadoVuelo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldEstadoVuelo.setBorder(null);
        add(jTextFieldEstadoVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 576, 329, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Estado de vuelo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 576, -1, -1));

        jTextFieldCantidad.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCantidad.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldCantidad.setText("0");
        jTextFieldCantidad.setBorder(null);
        jTextFieldCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadActionPerformed(evt);
            }
        });
        add(jTextFieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 636, 29, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel6.setText("Hay");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 636, -1, -1));

        jLabelVuelosEnEspera.setBackground(new java.awt.Color(144, 202, 249));
        jLabelVuelosEnEspera.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabelVuelosEnEspera.setText("Vuelos en espera");
        add(jLabelVuelosEnEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 636, -1, -1));

        jButton1EliminarUltimo.setBackground(new java.awt.Color(144, 202, 249));
        jButton1EliminarUltimo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1EliminarUltimo.setText("Eliminar primer vuelo agregado");
        jButton1EliminarUltimo.setBorder(null);
        jButton1EliminarUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1EliminarUltimoActionPerformed(evt);
            }
        });
        add(jButton1EliminarUltimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 636, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 116, 290, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 176, 290, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 236, 290, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 296, 290, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 356, 290, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 416, 290, 10));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 476, 290, 10));

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 536, 290, 10));

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 596, 290, 10));

        jLabelTituloAregarAvion.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        jLabelTituloAregarAvion.setText("Agregar vuelo");
        add(jLabelTituloAregarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 26, 170, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, -1));

        jButtonAgregarNuevoCliente.setBackground(new java.awt.Color(144, 202, 249));
        jButtonAgregarNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_control_point_black_18dp.png"))); // NOI18N
        jButtonAgregarNuevoCliente.setBorderPainted(false);
        jButtonAgregarNuevoCliente.setContentAreaFilled(false);
        jButtonAgregarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarNuevoClienteActionPerformed(evt);
            }
        });
        add(jButtonAgregarNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 670, 50, 40));

        jButtonVolver2.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver2.setBorder(null);
        jButtonVolver2.setContentAreaFilled(false);
        jButtonVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver2ActionPerformed(evt);
            }
        });
        add(jButtonVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDVueloActionPerformed

    private void jTextFieldCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadActionPerformed

    private void jButton1EliminarUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1EliminarUltimoActionPerformed
        if (principal.controladorColaVuelo.colaVacia()) {
            JOptionPane.showMessageDialog(this, "No hay vuelos", "Error al eliminar vuelo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            eliminarUltimo();
            mostrarCantVuelos();
        }
    }//GEN-LAST:event_jButton1EliminarUltimoActionPerformed

    private void jTextFieldHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraSalidaActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jButtonAgregarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarNuevoClienteActionPerformed
        agregar();
        mostrarCantVuelos();
    }//GEN-LAST:event_jButtonAgregarNuevoClienteActionPerformed

    private void jButtonVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver2ActionPerformed
        volver();
    }//GEN-LAST:event_jButtonVolver2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1EliminarUltimo;
    private javax.swing.JButton jButtonAgregarNuevoCliente;
    private javax.swing.JButton jButtonVolver2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelTituloAregarAvion;
    private javax.swing.JLabel jLabelVuelosEnEspera;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCiudadLlegada;
    private javax.swing.JTextField jTextFieldCiudadOrigen;
    private javax.swing.JTextField jTextFieldEstadoVuelo;
    private javax.swing.JTextField jTextFieldFechaRegreso;
    private javax.swing.JTextField jTextFieldFechaSalida;
    private javax.swing.JTextField jTextFieldHoraRegreso;
    private javax.swing.JTextField jTextFieldHoraSalida;
    private javax.swing.JTextField jTextFieldIDVuelo;
    private javax.swing.JTextField jTextFieldNumeroPasajeros;
    // End of variables declaration//GEN-END:variables

//    private void agregarYVolver() {
//        String idVuelo = jTextFieldIDVuelo.getText();
//        String fechaSalida = jTextFieldFechaSalida.getText();
//        String fechaRegreso = jTextFieldFechaRegreso.getText();
//        String horaSalida = jTextFieldHoraSalida.getText();
//        String horaRegreso = jTextFieldHoraRegreso.getText();
//        String ciudadOrigen = jTextFieldCiudadOrigen.getText();
//        String ciudadLlegada = jTextFieldCiudadLlegada.getText();
//        String numeroPasajerosString = jTextFieldNumeroPasajeros.getText();
//        int numeroPasajeros = Integer.parseInt(numeroPasajerosString);
//        boolean estadoVuelo = false;
//        Vuelo actual = new Vuelo(idVuelo, fechaSalida, fechaRegreso, horaSalida, horaRegreso, ciudadOrigen, ciudadLlegada, numeroPasajeros, estadoVuelo);
//        System.out.println(actual);
//        boolean valor = principal.controladorColaVuelo.agregarVuelo(actual);
//        if (valor == false) {
//            JOptionPane.showMessageDialog(this, "El vuelo ya existe", "Error al agregar la  nuevo vuelo", JOptionPane.INFORMATION_MESSAGE);
//        } else if (valor == true) {
//            System.out.println(principal.controladorColaVuelo.getTamanio());
//            principal.volverAGestionVuelos(this);
//        }
//    }
    private void volver() {
        principal.volverAGestionVuelosPresidente(this);

    }

    private void agregar() {
        try {
            String idVuelo = jTextFieldIDVuelo.getText();
            String fechaIda = jTextFieldFechaSalida.getText();
            String fechaRegreso = jTextFieldFechaRegreso.getText();
            String horaIda = jTextFieldHoraSalida.getText();
            String horaRegreso = jTextFieldHoraRegreso.getText();
            String ciudadIda = jTextFieldCiudadOrigen.getText();
            String ciudadRegreso = jTextFieldCiudadLlegada.getText();
            String numeroPasajerosString = jTextFieldNumeroPasajeros.getText();
            int cantDePasajeros = Integer.parseInt(numeroPasajerosString);
            String estado = jTextFieldEstadoVuelo.getText();
            Vuelo actual = new Vuelo(idVuelo, fechaIda, fechaRegreso, horaIda, horaRegreso, ciudadIda, ciudadRegreso, cantDePasajeros, estado);
            if (principal.controladorColaVuelo.validarExiste(actual)) {
                Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
                JOptionPane.showMessageDialog(this, "El vuelo ya existe", "Error al agregar el nuevo vuelo", JOptionPane.INFORMATION_MESSAGE,imagenError);
            } else {
                principal.controladorColaVuelo.agregarVuelo(actual);
                System.out.println(actual);
                System.out.println(principal.controladorColaVuelo.tamanioCola());
            }

        } catch (java.lang.NumberFormatException e2) {
            Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
            JOptionPane.showMessageDialog(this, "Tiene un campo donde el valor no es valido o esta vacio", "Error al agregar el nuevo vuelo", JOptionPane.INFORMATION_MESSAGE, imagenError);

        }
    }

    private void mostrarCantVuelos() {

        String cantVuelos = Integer.toString(principal.controladorColaVuelo.tamanioCola());

        jTextFieldCantidad.setText(cantVuelos);

    }

    public void eliminarUltimo() {

        principal.controladorColaVuelo.cancelarVuelo();
    }

}
