/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.awt.Frame.ICONIFIED;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nemac
 */
public class AgregarTrabajadorPresidenteJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form AgregarTrabajadorPresidenteJPanel
     */
    public AgregarTrabajadorPresidenteJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabelMatricula11 = new javax.swing.JLabel();
        jLabelMatricula12 = new javax.swing.JLabel();
        jTextFieldMatricula5 = new javax.swing.JTextField();
        jTextFieldMatricula6 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabelMatricula15 = new javax.swing.JLabel();
        jLabelMatricula16 = new javax.swing.JLabel();
        jTextFieldMatricula9 = new javax.swing.JTextField();
        jTextFieldMatricula10 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabelMatricula3 = new javax.swing.JLabel();
        jLabelMatricula4 = new javax.swing.JLabel();
        jButtonVolver1 = new javax.swing.JButton();
        jButtonAgregarNuevoAvion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelTituloAregarAvion = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldMatricula1 = new javax.swing.JTextField();
        jTextFieldMatricula2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelMatricula9 = new javax.swing.JLabel();
        jLabelMatricula10 = new javax.swing.JLabel();
        jTextFieldMatricula3 = new javax.swing.JTextField();
        jTextFieldMatricula4 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabelMatricula13 = new javax.swing.JLabel();
        jLabelMatricula14 = new javax.swing.JLabel();
        jTextFieldMatricula7 = new javax.swing.JTextField();
        jTextFieldMatricula8 = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabelMatricula17 = new javax.swing.JLabel();
        jLabelMatricula18 = new javax.swing.JLabel();
        jTextFieldMatricula11 = new javax.swing.JTextField();
        jTextFieldMatricula12 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabelMatricula19 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMatricula11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula11.setText("Matricula:");

        jLabelMatricula12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula12.setText("Matricula:");

        jTextFieldMatricula5.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula5.setBorder(null);
        jTextFieldMatricula5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula5ActionPerformed(evt);
            }
        });
        jTextFieldMatricula5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula5KeyTyped(evt);
            }
        });

        jTextFieldMatricula6.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula6.setBorder(null);
        jTextFieldMatricula6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula6ActionPerformed(evt);
            }
        });
        jTextFieldMatricula6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula6KeyTyped(evt);
            }
        });

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator12.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMatricula15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula15.setText("Matricula:");

        jLabelMatricula16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula16.setText("Matricula:");

        jTextFieldMatricula9.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula9.setBorder(null);
        jTextFieldMatricula9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula9ActionPerformed(evt);
            }
        });
        jTextFieldMatricula9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula9KeyTyped(evt);
            }
        });

        jTextFieldMatricula10.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula10.setBorder(null);
        jTextFieldMatricula10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula10ActionPerformed(evt);
            }
        });
        jTextFieldMatricula10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula10KeyTyped(evt);
            }
        });

        jSeparator13.setBackground(new java.awt.Color(0, 0, 0));

        setBackground(new java.awt.Color(144, 202, 249));

        jLabelMatricula3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula3.setText("ID:");

        jLabelMatricula4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula4.setText("Nombre:");

        jButtonVolver1.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver1.setBorder(null);
        jButtonVolver1.setContentAreaFilled(false);
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });

        jButtonAgregarNuevoAvion.setBackground(new java.awt.Color(144, 202, 249));
        jButtonAgregarNuevoAvion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarNuevoAvion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_control_point_black_18dp.png"))); // NOI18N
        jButtonAgregarNuevoAvion.setBorderPainted(false);
        jButtonAgregarNuevoAvion.setContentAreaFilled(false);
        jButtonAgregarNuevoAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarNuevoAvionActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        jLabelTituloAregarAvion.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        jLabelTituloAregarAvion.setText("Agregar trabajador");

        jTextFieldMatricula.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula.setBorder(null);
        jTextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaActionPerformed(evt);
            }
        });
        jTextFieldMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatriculaKeyTyped(evt);
            }
        });

        jTextFieldMatricula1.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula1.setBorder(null);
        jTextFieldMatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula1ActionPerformed(evt);
            }
        });
        jTextFieldMatricula1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula1KeyTyped(evt);
            }
        });

        jTextFieldMatricula2.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula2.setBorder(null);
        jTextFieldMatricula2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula2ActionPerformed(evt);
            }
        });
        jTextFieldMatricula2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula2KeyTyped(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMatricula9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula9.setText("Apellido:");

        jLabelMatricula10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula10.setText("CC:");

        jTextFieldMatricula3.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula3.setBorder(null);
        jTextFieldMatricula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula3ActionPerformed(evt);
            }
        });
        jTextFieldMatricula3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula3KeyTyped(evt);
            }
        });

        jTextFieldMatricula4.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula4.setBorder(null);
        jTextFieldMatricula4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula4ActionPerformed(evt);
            }
        });
        jTextFieldMatricula4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula4KeyTyped(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMatricula13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula13.setText("Tipo:");

        jLabelMatricula14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula14.setText("Nacionalidad:");

        jTextFieldMatricula7.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula7.setBorder(null);
        jTextFieldMatricula7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula7ActionPerformed(evt);
            }
        });
        jTextFieldMatricula7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula7KeyTyped(evt);
            }
        });

        jTextFieldMatricula8.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula8.setBorder(null);
        jTextFieldMatricula8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula8ActionPerformed(evt);
            }
        });
        jTextFieldMatricula8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula8KeyTyped(evt);
            }
        });

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMatricula17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula17.setText("Genero:");

        jLabelMatricula18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula18.setText("Correo:");

        jTextFieldMatricula11.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula11.setBorder(null);
        jTextFieldMatricula11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula11ActionPerformed(evt);
            }
        });
        jTextFieldMatricula11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula11KeyTyped(evt);
            }
        });

        jTextFieldMatricula12.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula12.setBorder(null);
        jTextFieldMatricula12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula12ActionPerformed(evt);
            }
        });
        jTextFieldMatricula12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula12KeyTyped(evt);
            }
        });

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMatricula19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula19.setText("Correo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVolver1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregarNuevoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTituloAregarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelCerrar)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMatricula18)
                            .addComponent(jLabelMatricula17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMatricula12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMatricula14)
                            .addComponent(jLabelMatricula13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMatricula8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMatricula10)
                            .addComponent(jLabelMatricula9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMatricula4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMatricula4)
                            .addComponent(jLabelMatricula3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jTextFieldMatricula2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(14, 14, 14))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(26, 26, 26))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(jTextFieldMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap()))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMatricula11, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMatricula7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(jLabelMatricula19)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabelTituloAregarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15)
                                        .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabelCerrar))
                                .addGap(8, 8, 8)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelMatricula3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelMatricula4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldMatricula2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMatricula9)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMatricula10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldMatricula4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMatricula13)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMatricula7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMatricula14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldMatricula8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelMatricula17)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldMatricula11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabelMatricula18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldMatricula12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAgregarNuevoAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(374, Short.MAX_VALUE)
                    .addComponent(jLabelMatricula19)
                    .addGap(101, 101, 101)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        principal.volverAGestionTrabajadorPresidente(this);
    }//GEN-LAST:event_jButtonVolver1ActionPerformed

    private void jButtonAgregarNuevoAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarNuevoAvionActionPerformed
        agregar();
    }//GEN-LAST:event_jButtonAgregarNuevoAvionActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jTextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaActionPerformed

    private void jTextFieldMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonAgregarNuevoAvion.doClick();
        }
    }//GEN-LAST:event_jTextFieldMatriculaKeyTyped

    private void jTextFieldMatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula1ActionPerformed

    private void jTextFieldMatricula1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula1KeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonAgregarNuevoAvion.doClick();
        }
    }//GEN-LAST:event_jTextFieldMatricula1KeyTyped

    private void jTextFieldMatricula2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula2ActionPerformed

    private void jTextFieldMatricula2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula2KeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonAgregarNuevoAvion.doClick();
        }
    }//GEN-LAST:event_jTextFieldMatricula2KeyTyped

    private void jTextFieldMatricula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula3ActionPerformed

    private void jTextFieldMatricula3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula3KeyTyped

    private void jTextFieldMatricula4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula4ActionPerformed

    private void jTextFieldMatricula4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula4KeyTyped

    private void jTextFieldMatricula5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula5ActionPerformed

    private void jTextFieldMatricula5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula5KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula5KeyTyped

    private void jTextFieldMatricula6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula6ActionPerformed

    private void jTextFieldMatricula6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula6KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula6KeyTyped

    private void jTextFieldMatricula7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula7ActionPerformed

    private void jTextFieldMatricula7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula7KeyTyped

    private void jTextFieldMatricula8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula8ActionPerformed

    private void jTextFieldMatricula8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula8KeyTyped

    private void jTextFieldMatricula9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula9ActionPerformed

    private void jTextFieldMatricula9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula9KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula9KeyTyped

    private void jTextFieldMatricula10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula10ActionPerformed

    private void jTextFieldMatricula10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula10KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula10KeyTyped

    private void jTextFieldMatricula11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula11ActionPerformed

    private void jTextFieldMatricula11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula11KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula11KeyTyped

    private void jTextFieldMatricula12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula12ActionPerformed

    private void jTextFieldMatricula12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula12KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula12KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarNuevoAvion;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelMatricula10;
    private javax.swing.JLabel jLabelMatricula11;
    private javax.swing.JLabel jLabelMatricula12;
    private javax.swing.JLabel jLabelMatricula13;
    private javax.swing.JLabel jLabelMatricula14;
    private javax.swing.JLabel jLabelMatricula15;
    private javax.swing.JLabel jLabelMatricula16;
    private javax.swing.JLabel jLabelMatricula17;
    private javax.swing.JLabel jLabelMatricula18;
    private javax.swing.JLabel jLabelMatricula19;
    private javax.swing.JLabel jLabelMatricula3;
    private javax.swing.JLabel jLabelMatricula4;
    private javax.swing.JLabel jLabelMatricula9;
    private javax.swing.JLabel jLabelTituloAregarAvion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public javax.swing.JTextField jTextFieldMatricula;
    public javax.swing.JTextField jTextFieldMatricula1;
    public javax.swing.JTextField jTextFieldMatricula10;
    public javax.swing.JTextField jTextFieldMatricula11;
    public javax.swing.JTextField jTextFieldMatricula12;
    public javax.swing.JTextField jTextFieldMatricula2;
    public javax.swing.JTextField jTextFieldMatricula3;
    public javax.swing.JTextField jTextFieldMatricula4;
    public javax.swing.JTextField jTextFieldMatricula5;
    public javax.swing.JTextField jTextFieldMatricula6;
    public javax.swing.JTextField jTextFieldMatricula7;
    public javax.swing.JTextField jTextFieldMatricula8;
    public javax.swing.JTextField jTextFieldMatricula9;
    // End of variables declaration//GEN-END:variables

    public void volver() {
        principal.volverAGestionTrabajadorPresidente(this);
    }

    public void agregar() {

    }
}
