/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelador.Avion;
import controlador.ControladorPilaAvion;
import controlador.ListaCircularClientes;
import static java.awt.Frame.ICONIFIED;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelador.Cliente;

/**
 *
 * @author Toshiba
 */
public class AgregarClienteDirectorJPanel extends javax.swing.JPanel {

    public static final String AGREGAR = "Agregar";
    public static final String ELIMINAR = "Eliminar";
    public static final String NUEVO = "Nuevo";
    public static final String BUSCAR = "Buscar";

    private Principal principal;
    public ListaCircularClientes listaCircularCliente;

    /**
     * Creates new form AgregarAeronavePresidente
     */
    public AgregarClienteDirectorJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolver = new javax.swing.JButton();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jLabelCantidadAsientos = new javax.swing.JLabel();
        jLabelCostoMantenimiento = new javax.swing.JLabel();
        jLabelCostohangar = new javax.swing.JLabel();
        jLabelCantidadEquipajeSoporado = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCC = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelMarca1 = new javax.swing.JLabel();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jLabelMarca2 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldCantidadAsientos1 = new javax.swing.JTextField();
        jComboBoxVisa = new javax.swing.JComboBox<>();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabelTituloAregarAvion = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jButtonAgregarNuevoCliente = new javax.swing.JButton();
        jButtonVolver2 = new javax.swing.JButton();
        jLabelCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButtonVolver.setBackground(new java.awt.Color(153, 0, 0));
        jButtonVolver.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(144, 202, 249));

        jLabelMatricula.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMatricula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula.setText("Nombre");

        jLabelMarca.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setText("Apellido");

        jLabelCantidadAsientos.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCantidadAsientos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidadAsientos.setText("CC");

        jLabelCostoMantenimiento.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCostoMantenimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCostoMantenimiento.setText("Telefono");

        jLabelCostohangar.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCostohangar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCostohangar.setText("Visa");

        jLabelCantidadEquipajeSoporado.setBackground(new java.awt.Color(0, 0, 0));
        jLabelCantidadEquipajeSoporado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidadEquipajeSoporado.setText("Genero");

        jTextFieldNombre.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jTextFieldCC.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCC.setBorder(null);
        jTextFieldCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCCActionPerformed(evt);
            }
        });
        jTextFieldCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCCKeyTyped(evt);
            }
        });

        jTextFieldApellido.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldApellido.setBorder(null);
        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyTyped(evt);
            }
        });

        jLabelMarca1.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMarca1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca1.setText("Nacionalidad");

        jTextFieldNacionalidad.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldNacionalidad.setBorder(null);
        jTextFieldNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNacionalidadKeyTyped(evt);
            }
        });

        jLabelMarca2.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMarca2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca2.setText("Correo");

        jTextFieldCorreo.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCorreo.setBorder(null);
        jTextFieldCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCorreoKeyTyped(evt);
            }
        });

        jTextFieldCantidadAsientos1.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCantidadAsientos1.setBorder(null);
        jTextFieldCantidadAsientos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantidadAsientos1ActionPerformed(evt);
            }
        });
        jTextFieldCantidadAsientos1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadAsientos1KeyTyped(evt);
            }
        });

        jComboBoxVisa.setBackground(new java.awt.Color(144, 202, 249));
        jComboBoxVisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si lo tiene", "No lo tiene" }));
        jComboBoxVisa.setBorder(null);
        jComboBoxVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVisaActionPerformed(evt);
            }
        });

        jComboBoxGenero.setBackground(new java.awt.Color(144, 202, 249));
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        jComboBoxGenero.setBorder(null);
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        jLabelTituloAregarAvion.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        jLabelTituloAregarAvion.setText("Agregar cliente");

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));

        jButtonAgregarNuevoCliente.setBackground(new java.awt.Color(144, 202, 249));
        jButtonAgregarNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregarNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_control_point_black_18dp.png"))); // NOI18N
        jButtonAgregarNuevoCliente.setBorderPainted(false);
        jButtonAgregarNuevoCliente.setContentAreaFilled(false);
        jButtonAgregarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarNuevoClienteActionPerformed(evt);
            }
        });

        jButtonVolver2.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver2.setBorder(null);
        jButtonVolver2.setContentAreaFilled(false);
        jButtonVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver2ActionPerformed(evt);
            }
        });

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelCerrar)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelMatricula)
                        .addGap(146, 146, 146)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelMarca)
                        .addGap(145, 145, 145)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelCantidadAsientos)
                        .addGap(176, 176, 176)
                        .addComponent(jTextFieldCC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelCantidadEquipajeSoporado)
                        .addGap(279, 279, 279)
                        .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jTextFieldNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelMarca2)
                        .addGap(152, 152, 152)
                        .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabelCostoMantenimiento)
                        .addGap(141, 141, 141)
                        .addComponent(jTextFieldCantidadAsientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVolver2)
                            .addComponent(jLabelCostohangar))
                        .addGap(297, 297, 297)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxVisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAgregarNuevoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelTituloAregarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCerrar)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelTituloAregarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatricula)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMarca)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCantidadAsientos)
                            .addComponent(jTextFieldCC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCantidadEquipajeSoporado)
                            .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMarca1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextFieldNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMarca2)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCostoMantenimiento)
                            .addComponent(jTextFieldCantidadAsientos1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCostohangar)
                            .addComponent(jComboBoxVisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jButtonVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAgregarNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCActionPerformed

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonAgregarNuevoCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonAgregarNuevoCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldApellidoKeyTyped

    private void jTextFieldCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCCKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonAgregarNuevoCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldCCKeyTyped

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        principal.volverAInicio(this);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jTextFieldNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNacionalidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNacionalidadKeyTyped

    private void jTextFieldCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoKeyTyped

    private void jTextFieldCantidadAsientos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantidadAsientos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadAsientos1ActionPerformed

    private void jTextFieldCantidadAsientos1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadAsientos1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantidadAsientos1KeyTyped

    private void jComboBoxVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVisaActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jButtonAgregarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarNuevoClienteActionPerformed
        agregar();
    }//GEN-LAST:event_jButtonAgregarNuevoClienteActionPerformed

    private void jButtonVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver2ActionPerformed
        volver();
    }//GEN-LAST:event_jButtonVolver2ActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregarNuevoCliente;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JButton jButtonVolver2;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxVisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCantidadAsientos;
    private javax.swing.JLabel jLabelCantidadEquipajeSoporado;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelCostoMantenimiento;
    private javax.swing.JLabel jLabelCostohangar;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelMarca1;
    private javax.swing.JLabel jLabelMarca2;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelTituloAregarAvion;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldCantidadAsientos1;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNacionalidad;
    public javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    public void agregar() {
        try {
            String nombre = jTextFieldNombre.getText();
            String apellido = jTextFieldApellido.getText();
            String ccString = jTextFieldCC.getText();
            int cc = Integer.parseInt(ccString);
            String generoString = jComboBoxGenero.getActionCommand();
            char genero = generoString.charAt(1);
            String nacionalidad = jTextFieldNacionalidad.getText();
            String correo = jTextFieldCorreo.getText();
            String telefonoString = jTextFieldCC.getText();
            int telefono = Integer.parseInt(telefonoString);
            String visaString = jComboBoxVisa.getActionCommand();;
            boolean visa = false;
            if (visaString.equals("Si lo tiene")) {
                visa = true;
            } else {
                visa = false;
            }
            Cliente actual = new Cliente(nombre, apellido, cc, genero, nacionalidad, correo, telefono, visa);
            boolean valor = principal.listaCircularCliente.agregarCabeza(actual);
            System.out.println(actual);
            if (valor == false) {
                Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
                JOptionPane.showMessageDialog(this, "El cliente ya existe", "Error al agregar el nuevo cliente", JOptionPane.INFORMATION_MESSAGE,imagenError);
            } else {
                principal.listaCircularCliente.agregarCabeza(actual);
                principal.volverAGestionClienteDirector(this);
            }
            System.out.println("cuantos" + principal.listaCircularCliente.getCantidad());
        } catch (java.lang.NumberFormatException e2) {
            Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
            JOptionPane.showMessageDialog(this, "Tiene un campo donde el valor no es valido o esta vacio", "Error al agregar el nuevo cliente", JOptionPane.INFORMATION_MESSAGE, imagenError);
        }
    }

    public void actualizarListaAviones() {
        String[] aviones = principal.controladorPilaAvion.darAviones();
    }

    private void volver() {
        principal.volverAGestionClienteDirector(this);
    }
}
