/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.awt.Frame.ICONIFIED;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelador.Cliente;

/**
 *
 * @author Toshiba
 */
public class BuscarClientePresidenteJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form BuscarAeronavePresidente
     */
    public BuscarClientePresidenteJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMatricula = new javax.swing.JLabel();
        CCBuscado = new javax.swing.JTextField();
        jTextFieldBuscado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelTituloAregarAvion = new javax.swing.JLabel();
        jButtonVolver1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(144, 202, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMatricula.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMatricula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula.setText("CC:");
        add(jLabelMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        CCBuscado.setBackground(new java.awt.Color(144, 202, 249));
        CCBuscado.setBorder(null);
        CCBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CCBuscadoKeyTyped(evt);
            }
        });
        add(CCBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 230, 20));

        jTextFieldBuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscadoActionPerformed(evt);
            }
        });
        add(jTextFieldBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 459, 106));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 230, 10));

        jButtonBuscarCliente.setBackground(new java.awt.Color(144, 202, 249));
        jButtonBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_search_black_24dp.png"))); // NOI18N
        jButtonBuscarCliente.setBorder(null);
        jButtonBuscarCliente.setBorderPainted(false);
        jButtonBuscarCliente.setContentAreaFilled(false);
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });
        add(jButtonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, -1));

        jLabelTituloAregarAvion.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        jLabelTituloAregarAvion.setText(" Buscar cliente");
        add(jLabelTituloAregarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 170, 48));

        jButtonVolver1.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver1.setBorder(null);
        jButtonVolver1.setContentAreaFilled(false);
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });
        add(jButtonVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 30, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void CCBuscadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CCBuscadoKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonBuscarCliente.doClick();
        }
    }//GEN-LAST:event_CCBuscadoKeyTyped

    private void jTextFieldBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscadoActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        try {
            buscar();
        } catch (java.lang.NullPointerException e1) {
                            Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
            JOptionPane.showMessageDialog(this, "El cliente no existe", "Error al buscar al cliente", JOptionPane.INFORMATION_MESSAGE,imagenError);
        }
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        principal.volverAGestionClientePresidente(this);
    }//GEN-LAST:event_jButtonVolver1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCBuscado;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelTituloAregarAvion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldBuscado;
    // End of variables declaration//GEN-END:variables

    private void buscar() {
        String ccString = CCBuscado.getText();
        int cc = Integer.parseInt(ccString);
        System.out.println(principal.listaCircularCliente.getCantidad());
        Cliente actual = principal.listaCircularCliente.buscar(cc);
        if (actual != null) {
            System.out.println("si esta");
        } else {
            System.out.println("no esta");
        }
        llenar(actual);
    }

    public void llenar(Cliente Actual) {
        Cliente actual = Actual;
        String prueba = actual.toString();
        jTextFieldBuscado.setText(prueba);
    }
}
