/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Toshiba
 */
public class EliminarClienteDirectorJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form EliminarAeronavePresidente
     */
    public EliminarClienteDirectorJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldCC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelTituloAregarAvion = new javax.swing.JLabel();
        jButtonEliminarCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonVolver2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(144, 202, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMatricula.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula.setText("CC:");
        add(jLabelMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jTextFieldCC.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCC.setBorder(null);
        jTextFieldCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCCActionPerformed(evt);
            }
        });
        jTextFieldCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCCKeyTyped(evt);
            }
        });
        add(jTextFieldCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, -1, -1));

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        jLabelTituloAregarAvion.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        jLabelTituloAregarAvion.setText(" Eliminar cliente");
        add(jLabelTituloAregarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, -1));

        jButtonEliminarCliente.setBackground(new java.awt.Color(144, 202, 249));
        jButtonEliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_delete_black_18dp.png"))); // NOI18N
        jButtonEliminarCliente.setBorderPainted(false);
        jButtonEliminarCliente.setContentAreaFilled(false);
        jButtonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarClienteActionPerformed(evt);
            }
        });
        jButtonEliminarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonEliminarClienteKeyTyped(evt);
            }
        });
        add(jButtonEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 60, 50));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 220, 10));

        jButtonVolver2.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver2.setBorder(null);
        jButtonVolver2.setContentAreaFilled(false);
        jButtonVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver2ActionPerformed(evt);
            }
        });
        add(jButtonVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCCKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonEliminarCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldCCKeyTyped

    private void jTextFieldCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jButtonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarClienteActionPerformed
        try {
            borrar();
        } catch (java.lang.NullPointerException e1) {
            Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
            JOptionPane.showMessageDialog(this, "El cliente no existe", "Error al eliminar al cliente", JOptionPane.INFORMATION_MESSAGE, imagenError);
        } catch (java.lang.ArrayIndexOutOfBoundsException e2) {
            Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
            JOptionPane.showMessageDialog(this, "El cliente no existe", "Error al eliminar al cliente", JOptionPane.INFORMATION_MESSAGE, imagenError);
        } catch (java.lang.NegativeArraySizeException e3) {
            borrar();
        }
    }//GEN-LAST:event_jButtonEliminarClienteActionPerformed

    private void jButtonEliminarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonEliminarClienteKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonEliminarCliente.doClick();
        }
    }//GEN-LAST:event_jButtonEliminarClienteKeyTyped

    private void jButtonVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver2ActionPerformed
        volver();
    }//GEN-LAST:event_jButtonVolver2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarCliente;
    private javax.swing.JButton jButtonVolver2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelTituloAregarAvion;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextFieldCC;
    // End of variables declaration//GEN-END:variables

    private void borrar() {
        String ccString = jTextFieldCC.getText();
        int cc = Integer.parseInt(ccString);
        principal.listaCircularCliente.eliminarPorDato(cc);
        principal.volverAGestionClientePresidente(this);
        volver();
    }

    private void volver() {
        principal.volverAGestionClienteDirector(this);
    }

}
