/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.awt.Frame.ICONIFIED;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nemac
 */
public class GestionTrabajadorPresidenteJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form GestionTrabajadoresPresidenteJPanel
     */
    public GestionTrabajadorPresidenteJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEliminarAeroanve = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonActualizar = new javax.swing.JButton();
        jButtonAgregarAeronave = new javax.swing.JButton();
        jButtonBuscarAeronave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonEliminarAeroanve1 = new javax.swing.JButton();
        jButtonModificarAeronave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButtonVolver1 = new javax.swing.JButton();
        jButtonActualizar1 = new javax.swing.JButton();

        jButtonEliminarAeroanve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_delete_black_24dp.png"))); // NOI18N
        jButtonEliminarAeroanve.setBorderPainted(false);
        jButtonEliminarAeroanve.setContentAreaFilled(false);
        jButtonEliminarAeroanve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAeroanveActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jButtonActualizar.setBackground(new java.awt.Color(153, 0, 0));
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_autorenew_black_18dp.png"))); // NOI18N
        jButtonActualizar.setBorder(null);
        jButtonActualizar.setBorderPainted(false);
        jButtonActualizar.setContentAreaFilled(false);
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(144, 202, 249));

        jButtonAgregarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_control_point_black_24dp.png"))); // NOI18N
        jButtonAgregarAeronave.setBorderPainted(false);
        jButtonAgregarAeronave.setContentAreaFilled(false);
        jButtonAgregarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAeronaveActionPerformed(evt);
            }
        });

        jButtonBuscarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_search_black_24dp.png"))); // NOI18N
        jButtonBuscarAeronave.setBorderPainted(false);
        jButtonBuscarAeronave.setContentAreaFilled(false);
        jButtonBuscarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAeronaveActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 102, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ISOLOGO USB (4).png"))); // NOI18N

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButtonEliminarAeroanve1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_delete_black_24dp.png"))); // NOI18N
        jButtonEliminarAeroanve1.setBorderPainted(false);
        jButtonEliminarAeroanve1.setContentAreaFilled(false);
        jButtonEliminarAeroanve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAeroanve1ActionPerformed(evt);
            }
        });

        jButtonModificarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_build_black_24dp.png"))); // NOI18N
        jButtonModificarAeronave.setBorderPainted(false);
        jButtonModificarAeronave.setContentAreaFilled(false);
        jButtonModificarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarAeronaveActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        jButtonVolver1.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver1.setBorder(null);
        jButtonVolver1.setContentAreaFilled(false);
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });

        jButtonActualizar1.setBackground(new java.awt.Color(153, 0, 0));
        jButtonActualizar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_autorenew_black_18dp.png"))); // NOI18N
        jButtonActualizar1.setBorder(null);
        jButtonActualizar1.setBorderPainted(false);
        jButtonActualizar1.setContentAreaFilled(false);
        jButtonActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAgregarAeronave)
                    .addComponent(jButtonEliminarAeroanve1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBuscarAeronave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonModificarAeronave))
                        .addGap(65, 65, 65))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabelCerrar)
                            .addGap(39, 39, 39))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(174, 174, 174)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(453, 453, 453)
                        .addComponent(jButtonActualizar1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCerrar)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAgregarAeronave)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarAeroanve1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBuscarAeronave)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonModificarAeronave)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonActualizar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAeronaveActionPerformed
        agregar();
    }//GEN-LAST:event_jButtonAgregarAeronaveActionPerformed

    private void jButtonBuscarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAeronaveActionPerformed
        buscar();
    }//GEN-LAST:event_jButtonBuscarAeronaveActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButtonEliminarAeroanveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAeroanveActionPerformed

    }//GEN-LAST:event_jButtonEliminarAeroanveActionPerformed

    private void jButtonEliminarAeroanve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAeroanve1ActionPerformed
        eliminar();
    }//GEN-LAST:event_jButtonEliminarAeroanve1ActionPerformed

    private void jButtonModificarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarAeronaveActionPerformed
        modificar();
    }//GEN-LAST:event_jButtonModificarAeronaveActionPerformed

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        volver();
    }//GEN-LAST:event_jButtonVolver1ActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        String[] aviones = principal.controladorPilaAvion.darAviones();
        jList1.setListData((String[]) aviones);
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizar1ActionPerformed
        String[] aviones = principal.controladorPilaAvion.darAviones();
        jList1.setListData((String[]) aviones);
    }//GEN-LAST:event_jButtonActualizar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonActualizar1;
    private javax.swing.JButton jButtonAgregarAeronave;
    private javax.swing.JButton jButtonBuscarAeronave;
    private javax.swing.JButton jButtonEliminarAeroanve;
    private javax.swing.JButton jButtonEliminarAeroanve1;
    private javax.swing.JButton jButtonModificarAeronave;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void volver() {
        principal.volverAPresidente(this);
    }

    public void modificar() {
        principal.irAModificarTrabajadorPresidente(this);
    }

    public void agregar() {
        principal.irAAgregarTrabajadorDirector(this);
    }

    public void buscar() {
        principal.irABuscarTrabajadorPresidente(this);
    }

    public void eliminar() {
        principal.irAEliminarTrabajadorPresidente(this);
    }
}
