/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.awt.Frame.ICONIFIED;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nemac
 */
public class GestionVuelosDirectorJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form GestionVuelosPresidenteJPanel
     */
    public GestionVuelosDirectorJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaColaVuelos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNumeroDeVuelos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonVolver1 = new javax.swing.JButton();
        jButtonActualizar1 = new javax.swing.JButton();
        jButtonAgregarAeronave1 = new javax.swing.JButton();
        jButtonBuscarAeronave = new javax.swing.JButton();
        jButtonModificarAeronave = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 202, 249));
        setPreferredSize(new java.awt.Dimension(552, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(144, 202, 249));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_cancel_black_24dp.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 60, -1));

        jTextAreaColaVuelos.setColumns(20);
        jTextAreaColaVuelos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaColaVuelos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 510, 120));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("Hay");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jTextFieldNumeroDeVuelos.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldNumeroDeVuelos.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jTextFieldNumeroDeVuelos.setBorder(null);
        jTextFieldNumeroDeVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroDeVuelosActionPerformed(evt);
            }
        });
        add(jTextFieldNumeroDeVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 20, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("vuelos en espera");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jButtonVolver1.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver1.setBorder(null);
        jButtonVolver1.setContentAreaFilled(false);
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });
        add(jButtonVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        jButtonActualizar1.setBackground(new java.awt.Color(153, 0, 0));
        jButtonActualizar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_autorenew_black_18dp.png"))); // NOI18N
        jButtonActualizar1.setBorder(null);
        jButtonActualizar1.setBorderPainted(false);
        jButtonActualizar1.setContentAreaFilled(false);
        jButtonActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizar1ActionPerformed(evt);
            }
        });
        add(jButtonActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, -1));

        jButtonAgregarAeronave1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_control_point_black_24dp.png"))); // NOI18N
        jButtonAgregarAeronave1.setBorderPainted(false);
        jButtonAgregarAeronave1.setContentAreaFilled(false);
        jButtonAgregarAeronave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarAeronave1ActionPerformed(evt);
            }
        });
        add(jButtonAgregarAeronave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jButtonBuscarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_search_black_24dp.png"))); // NOI18N
        jButtonBuscarAeronave.setBorderPainted(false);
        jButtonBuscarAeronave.setContentAreaFilled(false);
        jButtonBuscarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAeronaveActionPerformed(evt);
            }
        });
        add(jButtonBuscarAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 80, -1));

        jButtonModificarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_build_black_24dp.png"))); // NOI18N
        jButtonModificarAeronave.setBorderPainted(false);
        jButtonModificarAeronave.setContentAreaFilled(false);
        jButtonModificarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarAeronaveActionPerformed(evt);
            }
        });
        add(jButtonModificarAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 102, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ISOLOGO USB (4).png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 180, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, -1));

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cancelar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextFieldNumeroDeVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroDeVuelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroDeVuelosActionPerformed

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        volver();
    }//GEN-LAST:event_jButtonVolver1ActionPerformed

    private void jButtonActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizar1ActionPerformed
        if (principal.controladorColaVuelo.tamanioCola() > 0) {
            mostrarCola();
        } else {
            numVuelos();
            JOptionPane.showMessageDialog(this, "No hay vuelos en espera", "Error al mostrar vuelos en espera", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonActualizar1ActionPerformed

    private void jButtonAgregarAeronave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarAeronave1ActionPerformed
        agregar();
    }//GEN-LAST:event_jButtonAgregarAeronave1ActionPerformed

    private void jButtonBuscarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAeronaveActionPerformed
        buscar();
    }//GEN-LAST:event_jButtonBuscarAeronaveActionPerformed

    private void jButtonModificarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarAeronaveActionPerformed
        modificar();
    }//GEN-LAST:event_jButtonModificarAeronaveActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonActualizar1;
    private javax.swing.JButton jButtonAgregarAeronave1;
    private javax.swing.JButton jButtonBuscarAeronave;
    private javax.swing.JButton jButtonModificarAeronave;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaColaVuelos;
    private javax.swing.JTextField jTextFieldNumeroDeVuelos;
    // End of variables declaration//GEN-END:variables

    public void volver() {
        principal.volverADirector(this);
    }

    public void agregar() {
        principal.irAAgregarVueloDirector(this);
    }

    public void modificar() {
        principal.irAModificarVueloDirector(this);
    }

    public void cancelar() {
        principal.irACancelarVueloDirector(this);
    }

    public void buscar() {
        principal.irABuscarVueloDirector(this);
    }

    public void numVuelos() {
        int numero = principal.controladorColaVuelo.tamanioCola();
        String noVuelos = Integer.toString(numero);
        jTextFieldNumeroDeVuelos.setText(noVuelos);
    }

    public void mostrarCola() {
        String cola = principal.controladorColaVuelo.mostrarCola();
        System.out.println(cola);
        jTextAreaColaVuelos.setText(cola);
        numVuelos();
    }
}
