/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import static java.awt.Frame.ICONIFIED;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author nemac
 */
public class ModificarTrabajadorPresidenteJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form ModificarTrabajadorPresidenteJPanel
     */
    public ModificarTrabajadorPresidenteJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelTituloAregarAvion = new javax.swing.JLabel();
        jButtonVolver1 = new javax.swing.JButton();
        jButtonModificarTrabajador = new javax.swing.JButton();
        jLabelMatricula9 = new javax.swing.JLabel();
        jLabelMatricula10 = new javax.swing.JLabel();
        jTextFieldMatricula3 = new javax.swing.JTextField();
        jTextFieldMatricula4 = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabelMatricula13 = new javax.swing.JLabel();
        jLabelMatricula14 = new javax.swing.JLabel();
        jTextFieldMatricula7 = new javax.swing.JTextField();
        jLabelMatricula3 = new javax.swing.JLabel();
        jTextFieldMatricula8 = new javax.swing.JTextField();
        jLabelMatricula4 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabelMatricula17 = new javax.swing.JLabel();
        jLabelMatricula18 = new javax.swing.JLabel();
        jTextFieldMatricula11 = new javax.swing.JTextField();
        jTextFieldMatricula12 = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldMatricula1 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        jRadioButton1.setText("jRadioButton1");

        setBackground(new java.awt.Color(144, 202, 249));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });

        jLabelTituloAregarAvion.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        jLabelTituloAregarAvion.setText("Modificar trabajador");

        jButtonVolver1.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver1.setBorder(null);
        jButtonVolver1.setContentAreaFilled(false);
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });

        jButtonModificarTrabajador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_build_black_24dp.png"))); // NOI18N
        jButtonModificarTrabajador.setBorderPainted(false);
        jButtonModificarTrabajador.setContentAreaFilled(false);
        jButtonModificarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTrabajadorActionPerformed(evt);
            }
        });

        jLabelMatricula9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula9.setText("Matricula:");

        jLabelMatricula10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula10.setText("Matricula:");

        jTextFieldMatricula3.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula3.setBorder(null);
        jTextFieldMatricula3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula3ActionPerformed(evt);
            }
        });
        jTextFieldMatricula3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula3KeyTyped(evt);
            }
        });

        jTextFieldMatricula4.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula4.setBorder(null);
        jTextFieldMatricula4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula4ActionPerformed(evt);
            }
        });
        jTextFieldMatricula4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula4KeyTyped(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator10.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMatricula13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula13.setText("Matricula:");

        jLabelMatricula14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula14.setText("Matricula:");

        jTextFieldMatricula7.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula7.setBorder(null);
        jTextFieldMatricula7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula7ActionPerformed(evt);
            }
        });
        jTextFieldMatricula7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula7KeyTyped(evt);
            }
        });

        jLabelMatricula3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula3.setText("Matricula:");

        jTextFieldMatricula8.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula8.setBorder(null);
        jTextFieldMatricula8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula8ActionPerformed(evt);
            }
        });
        jTextFieldMatricula8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula8KeyTyped(evt);
            }
        });

        jLabelMatricula4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula4.setText("Matricula:");

        jSeparator11.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));

        jLabelMatricula17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula17.setText("Matricula:");

        jLabelMatricula18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMatricula18.setText("Matricula:");

        jTextFieldMatricula11.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula11.setBorder(null);
        jTextFieldMatricula11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula11ActionPerformed(evt);
            }
        });
        jTextFieldMatricula11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula11KeyTyped(evt);
            }
        });

        jTextFieldMatricula12.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula12.setBorder(null);
        jTextFieldMatricula12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula12ActionPerformed(evt);
            }
        });
        jTextFieldMatricula12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula12KeyTyped(evt);
            }
        });

        jTextFieldMatricula.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula.setBorder(null);
        jTextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaActionPerformed(evt);
            }
        });
        jTextFieldMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatriculaKeyTyped(evt);
            }
        });

        jTextFieldMatricula1.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula1.setBorder(null);
        jTextFieldMatricula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatricula1ActionPerformed(evt);
            }
        });
        jTextFieldMatricula1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatricula1KeyTyped(evt);
            }
        });

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVolver1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonModificarTrabajador)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 139, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelTituloAregarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCerrar)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMatricula11, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMatricula8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMatricula12, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMatricula7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMatricula4, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelMatricula18)
                                .addComponent(jLabelMatricula17))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelMatricula14)
                                .addComponent(jLabelMatricula13))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMatricula10)
                                    .addComponent(jLabelMatricula9))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelMatricula4)
                                    .addComponent(jLabelMatricula3)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(jSeparator2))))
                    .addGap(48, 48, 48)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelCerrar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelTituloAregarAvion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jTextFieldMatricula3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldMatricula4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jTextFieldMatricula7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldMatricula8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldMatricula11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldMatricula12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonModificarTrabajador)
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(143, 143, 143)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelMatricula3)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabelMatricula4)
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelMatricula9)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabelMatricula10))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelMatricula13)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabelMatricula14))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelMatricula17)
                        .addComponent(jSeparator15, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabelMatricula18))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(132, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        volver();
    }//GEN-LAST:event_jButtonVolver1ActionPerformed

    private void jButtonModificarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTrabajadorActionPerformed
        modificar();
    }//GEN-LAST:event_jButtonModificarTrabajadorActionPerformed

    private void jTextFieldMatricula3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula3ActionPerformed

    private void jTextFieldMatricula3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula3KeyTyped

    private void jTextFieldMatricula4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula4ActionPerformed

    private void jTextFieldMatricula4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula4KeyTyped

    private void jTextFieldMatricula7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula7ActionPerformed

    private void jTextFieldMatricula7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula7KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula7KeyTyped

    private void jTextFieldMatricula8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula8ActionPerformed

    private void jTextFieldMatricula8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula8KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula8KeyTyped

    private void jTextFieldMatricula11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula11ActionPerformed

    private void jTextFieldMatricula11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula11KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula11KeyTyped

    private void jTextFieldMatricula12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula12ActionPerformed

    private void jTextFieldMatricula12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula12KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula12KeyTyped

    private void jTextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaActionPerformed

    private void jTextFieldMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarTrabajador.doClick();
        }
    }//GEN-LAST:event_jTextFieldMatriculaKeyTyped

    private void jTextFieldMatricula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatricula1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatricula1ActionPerformed

    private void jTextFieldMatricula1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatricula1KeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarTrabajador.doClick();
        }
    }//GEN-LAST:event_jTextFieldMatricula1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarTrabajador;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelMatricula10;
    private javax.swing.JLabel jLabelMatricula13;
    private javax.swing.JLabel jLabelMatricula14;
    private javax.swing.JLabel jLabelMatricula17;
    private javax.swing.JLabel jLabelMatricula18;
    private javax.swing.JLabel jLabelMatricula3;
    private javax.swing.JLabel jLabelMatricula4;
    private javax.swing.JLabel jLabelMatricula9;
    private javax.swing.JLabel jLabelTituloAregarAvion;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JTextField jTextFieldMatricula;
    public javax.swing.JTextField jTextFieldMatricula1;
    public javax.swing.JTextField jTextFieldMatricula11;
    public javax.swing.JTextField jTextFieldMatricula12;
    public javax.swing.JTextField jTextFieldMatricula3;
    public javax.swing.JTextField jTextFieldMatricula4;
    public javax.swing.JTextField jTextFieldMatricula7;
    public javax.swing.JTextField jTextFieldMatricula8;
    // End of variables declaration//GEN-END:variables
    
    public void modificar() {

    }

    public void volver() {
        principal.volverAGestionTrabajadorPresidente(this);
    }

}
