/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelador.Avion;
import controlador.ControladorPilaAvion;
import static java.awt.Frame.ICONIFIED;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import modelador.Cliente;

/**
 *
 * @author Toshiba
 */
public class ModificarClientePresidenteJPanel extends javax.swing.JPanel {

    private Principal principal;
    private ControladorPilaAvion controladorPilaAvion;
    private Avion aviones;

    /**
     * Creates new form ModificarAeronavePresidente
     */
    public ModificarClientePresidenteJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCC = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldNacionalidad = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jComboBoxVisa = new javax.swing.JComboBox<>();
        jLabelCerrar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelTituloAregarAvion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jButtonBuscarCliente = new javax.swing.JButton();
        jButtonModificarCliente = new javax.swing.JButton();
        jButtonVolver2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(144, 202, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CC:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Apellido:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Genero");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Nacionalidad");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Correo");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Telefono");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jTextFieldCC.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCC.setBorder(null);
        jTextFieldCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCCActionPerformed(evt);
            }
        });
        jTextFieldCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCCKeyTyped(evt);
            }
        });
        add(jTextFieldCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 238, 20));

        jTextFieldNombre.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });
        add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 238, 20));

        jTextFieldApellido.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldApellido.setBorder(null);
        jTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellidoActionPerformed(evt);
            }
        });
        jTextFieldApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldApellidoKeyTyped(evt);
            }
        });
        add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 238, 20));

        jTextFieldNacionalidad.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldNacionalidad.setBorder(null);
        jTextFieldNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNacionalidadKeyTyped(evt);
            }
        });
        add(jTextFieldNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 414, 238, 20));

        jTextFieldCorreo.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCorreo.setBorder(null);
        jTextFieldCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCorreoKeyTyped(evt);
            }
        });
        add(jTextFieldCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 238, 20));

        jTextFieldTelefono.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldTelefono.setBorder(null);
        jTextFieldTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTelefonoKeyTyped(evt);
            }
        });
        add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 238, 20));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Vuelo");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

        jComboBoxGenero.setBackground(new java.awt.Color(144, 202, 249));
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jComboBoxGenero.setBorder(null);
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });
        add(jComboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jComboBoxVisa.setBackground(new java.awt.Color(144, 202, 249));
        jComboBoxVisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si lo tiene", "No llo tiene" }));
        jComboBoxVisa.setBorder(null);
        jComboBoxVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVisaActionPerformed(evt);
            }
        });
        add(jComboBoxVisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 590, -1, -1));

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        jLabelTituloAregarAvion.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        jLabelTituloAregarAvion.setText("Modificar cliente");
        add(jLabelTituloAregarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 240, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 240, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 240, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 240, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 240, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 240, 30));

        jButtonBuscarCliente.setBackground(new java.awt.Color(144, 202, 249));
        jButtonBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_search_black_24dp.png"))); // NOI18N
        jButtonBuscarCliente.setBorder(null);
        jButtonBuscarCliente.setBorderPainted(false);
        jButtonBuscarCliente.setContentAreaFilled(false);
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });
        add(jButtonBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jButtonModificarCliente.setBackground(new java.awt.Color(0, 102, 0));
        jButtonModificarCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_build_black_18dp.png"))); // NOI18N
        jButtonModificarCliente.setBorderPainted(false);
        jButtonModificarCliente.setContentAreaFilled(false);
        jButtonModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarClienteActionPerformed(evt);
            }
        });
        jButtonModificarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonModificarClienteKeyTyped(evt);
            }
        });
        add(jButtonModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 50, 50));

        jButtonVolver2.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver2.setBorder(null);
        jButtonVolver2.setContentAreaFilled(false);
        jButtonVolver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver2ActionPerformed(evt);
            }
        });
        add(jButtonVolver2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, -1, 40));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Visa");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCCActionPerformed

    private void jTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellidoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed

    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCCKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonBuscarCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldCCKeyTyped

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    private void jTextFieldApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidoKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldApellidoKeyTyped

    private void jTextFieldNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNacionalidadKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldNacionalidadKeyTyped

    private void jTextFieldCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCorreoKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldCorreoKeyTyped

    private void jTextFieldTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarCliente.doClick();
        }
    }//GEN-LAST:event_jTextFieldTelefonoKeyTyped

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jComboBoxVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVisaActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        try {
            buscarParaCC();
        } catch (java.lang.NullPointerException e1) {
            Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
            JOptionPane.showMessageDialog(this, "La aeronave no existe", "Error al buscar la aeronave", JOptionPane.INFORMATION_MESSAGE, imagenError);
        }
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarClienteActionPerformed
        borrar();
        agregar();
        principal.volverAGestionClientePresidente(this);
    }//GEN-LAST:event_jButtonModificarClienteActionPerformed

    private void jButtonModificarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonModificarClienteKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarCliente.doClick();
        }
    }//GEN-LAST:event_jButtonModificarClienteKeyTyped

    private void jButtonVolver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver2ActionPerformed
        principal.volverAGestionClientePresidente(this);
    }//GEN-LAST:event_jButtonVolver2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonModificarCliente;
    private javax.swing.JButton jButtonVolver2;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JComboBox<String> jComboBoxVisa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelTituloAregarAvion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCC;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNacionalidad;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables

    private void buscar() {
        String ccString = jTextFieldCC.getText();
        int cc = Integer.parseInt(ccString);
        System.out.println(principal.listaCircularCliente.getCantidad());
        Cliente actual = principal.listaCircularCliente.buscar(cc);
        if (actual != null) {
            System.out.println("si esta");
        } else {
            System.out.println("no esta");
        }
        llenarCampos(actual);
    }

    private void llenarCampos(Cliente actual) {
        String ccString = jTextFieldCC.getText();
        int cc = Integer.parseInt(ccString);
        jTextFieldNombre.setText(principal.getListaCircularCliente().buscar(cc).getNombreCliente());
        jTextFieldApellido.setText(principal.getListaCircularCliente().buscar(cc).getApellidoCliente());
        jTextFieldNacionalidad.setText(principal.getListaCircularCliente().buscar(cc).getNacionalidadCliente());
        jTextFieldCorreo.setText(principal.getListaCircularCliente().buscar(cc).getCorreoCliente());
        int telefonoInt = principal.getListaCircularCliente().buscar(cc).getTelefonoCliente();
        String telefonoString = Integer.toString(telefonoInt);
        jTextFieldTelefono.setText(telefonoString);
    }

    private void buscarParaCC() {
        String ccString = jTextFieldCC.getText();
        int cc = Integer.parseInt(ccString);
        System.out.println(principal.listaCircularCliente.getCantidad());
        Cliente actual = principal.listaCircularCliente.buscar(cc);
        if (actual != null) {
            System.out.println("si esta");
        } else {
            System.out.println("no esta");
        }
        llenarCampos(actual);
    }

    private void borrar() {
        String ccString = jTextFieldCC.getText();
        int cc = Integer.parseInt(ccString);
        principal.listaCircularCliente.eliminarPorDato(cc);
        actualizarListaCliente();;
        principal.volverAGestionClientePresidente(this);
    }

    private void actualizarListaAviones() {
        String[] aviones = principal.controladorPilaAvion.darAviones();
    }

    private void agregar() {
        try {
            String nombre = jTextFieldNombre.getText();
            String apellido = jTextFieldApellido.getText();
            String ccString = jTextFieldCC.getText();
            int cc = Integer.parseInt(ccString);
            String generoString = jComboBoxGenero.getActionCommand();
            char genero = generoString.charAt(1);
            String nacionalidad = jTextFieldNacionalidad.getText();
            String correo = jTextFieldCorreo.getText();
            String telefonoString = jTextFieldCC.getText();
            int telefono = Integer.parseInt(telefonoString);
            String visaString = jComboBoxVisa.getActionCommand();
            boolean visa = false;
            if (visaString == "Si lo tiene") {
                visa = true;
            } else {
                visa = false;
            }
            Cliente actual = new Cliente(nombre, apellido, cc, genero, nacionalidad, correo, telefono, visa);
            boolean valor = principal.listaCircularCliente.agregarCabeza(actual);
            System.out.println(actual);
            if (valor == false) {
                JOptionPane.showMessageDialog(this, "El cliente ya existe", "Error al agregar el nuevo cliente", JOptionPane.INFORMATION_MESSAGE);
            } else {
                principal.listaCircularCliente.agregarCabeza(actual);
                principal.volverAGestionClientePresidente(this);
            }
            System.out.println("cuantos" + principal.listaCircularCliente.getCantidad());
        } catch (java.lang.NumberFormatException e2) {
            JOptionPane.showMessageDialog(this, "Tiene un campo donde el valor no es valido o esta vacio", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void actualizarListaCliente() {
        String cliente = principal.listaCircularCliente.mostrarLista();
    }

}
