/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelador.Avion;
import controlador.ControladorPilaAvion;
import static java.awt.Frame.ICONIFIED;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author Toshiba
 */
public class ModificarAeronavePresidenteJPanel extends javax.swing.JPanel {

    private Principal principal;
    private ControladorPilaAvion controladorPilaAvion;
    private Avion aviones;

    /**
     * Creates new form ModificarAeronavePresidente
     */
    public ModificarAeronavePresidenteJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldCantidadAsientos = new javax.swing.JTextField();
        jTextFieldCantidadEquipaje = new javax.swing.JTextField();
        jTextFieldCostoMantenimiento = new javax.swing.JTextField();
        jTextFieldCostoHangar = new javax.swing.JTextField();
        jButtonModificarAeronave = new javax.swing.JButton();
        jLabelCostoMantenimiento = new javax.swing.JLabel();
        jLabelCantidadEquipajeSoporado = new javax.swing.JLabel();
        jLabelCantidadAsientos = new javax.swing.JLabel();
        jLabelModelo = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jButtonBuscarAeronave = new javax.swing.JButton();
        jButtonVolver1 = new javax.swing.JButton();
        jLabelTituloAregarAvion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelCerrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(144, 202, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Matricula:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Costo del hangar:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, 20));

        jTextFieldMatricula.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMatricula.setBorder(null);
        jTextFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMatriculaActionPerformed(evt);
            }
        });
        jTextFieldMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMatriculaKeyTyped(evt);
            }
        });
        add(jTextFieldMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 107, 240, 20));

        jTextFieldMarca.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldMarca.setBorder(null);
        jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaActionPerformed(evt);
            }
        });
        jTextFieldMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldMarcaKeyTyped(evt);
            }
        });
        add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 238, 20));

        jTextFieldModelo.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldModelo.setBorder(null);
        jTextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloActionPerformed(evt);
            }
        });
        jTextFieldModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldModeloKeyTyped(evt);
            }
        });
        add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 238, 20));

        jTextFieldCantidadAsientos.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCantidadAsientos.setBorder(null);
        jTextFieldCantidadAsientos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadAsientosKeyTyped(evt);
            }
        });
        add(jTextFieldCantidadAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 238, 20));

        jTextFieldCantidadEquipaje.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCantidadEquipaje.setBorder(null);
        jTextFieldCantidadEquipaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCantidadEquipajeKeyTyped(evt);
            }
        });
        add(jTextFieldCantidadEquipaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 238, 20));

        jTextFieldCostoMantenimiento.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCostoMantenimiento.setBorder(null);
        jTextFieldCostoMantenimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostoMantenimientoKeyTyped(evt);
            }
        });
        add(jTextFieldCostoMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, 238, 20));

        jTextFieldCostoHangar.setBackground(new java.awt.Color(144, 202, 249));
        jTextFieldCostoHangar.setBorder(null);
        jTextFieldCostoHangar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCostoHangarKeyTyped(evt);
            }
        });
        add(jTextFieldCostoHangar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 238, 20));

        jButtonModificarAeronave.setBackground(new java.awt.Color(0, 102, 0));
        jButtonModificarAeronave.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_build_black_18dp.png"))); // NOI18N
        jButtonModificarAeronave.setBorderPainted(false);
        jButtonModificarAeronave.setContentAreaFilled(false);
        jButtonModificarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarAeronaveActionPerformed(evt);
            }
        });
        jButtonModificarAeronave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonModificarAeronaveKeyTyped(evt);
            }
        });
        add(jButtonModificarAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 50, 50));

        jLabelCostoMantenimiento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCostoMantenimiento.setText("Costo de mantenimiento:");
        add(jLabelCostoMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 20));

        jLabelCantidadEquipajeSoporado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidadEquipajeSoporado.setText("Cantidad de equipaje soportado:");
        add(jLabelCantidadEquipajeSoporado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 20));

        jLabelCantidadAsientos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCantidadAsientos.setText("Cantidad de asientos:");
        add(jLabelCantidadAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jLabelModelo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelModelo.setText("Modelo:");
        add(jLabelModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 20));

        jLabelMarca.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelMarca.setText("Marca:");
        add(jLabelMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jButtonBuscarAeronave.setBackground(new java.awt.Color(144, 202, 249));
        jButtonBuscarAeronave.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonBuscarAeronave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_search_black_24dp.png"))); // NOI18N
        jButtonBuscarAeronave.setBorder(null);
        jButtonBuscarAeronave.setBorderPainted(false);
        jButtonBuscarAeronave.setContentAreaFilled(false);
        jButtonBuscarAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarAeronaveActionPerformed(evt);
            }
        });
        add(jButtonBuscarAeronave, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jButtonVolver1.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_18dp.png"))); // NOI18N
        jButtonVolver1.setBorder(null);
        jButtonVolver1.setContentAreaFilled(false);
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });
        add(jButtonVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, 30));

        jLabelTituloAregarAvion.setFont(new java.awt.Font("Harlow Solid Italic", 1, 24)); // NOI18N
        jLabelTituloAregarAvion.setText("Modificar avion");
        add(jLabelTituloAregarAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_black_18dp.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_black_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 240, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 240, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 240, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 240, 10));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 240, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 240, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 240, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarAeronaveActionPerformed
        borrar();
        agregar();
        principal.volverAGestionAeronavePresidente(this);
    }//GEN-LAST:event_jButtonModificarAeronaveActionPerformed

    private void jTextFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMatriculaActionPerformed

    private void jTextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloActionPerformed

    private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed

    }//GEN-LAST:event_jTextFieldMarcaActionPerformed

    private void jTextFieldMatriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMatriculaKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonBuscarAeronave.doClick();
        }
    }//GEN-LAST:event_jTextFieldMatriculaKeyTyped

    private void jTextFieldMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMarcaKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarAeronave.doClick();
        }
    }//GEN-LAST:event_jTextFieldMarcaKeyTyped

    private void jTextFieldModeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldModeloKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarAeronave.doClick();
        }
    }//GEN-LAST:event_jTextFieldModeloKeyTyped

    private void jTextFieldCantidadAsientosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadAsientosKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarAeronave.doClick();
        }
    }//GEN-LAST:event_jTextFieldCantidadAsientosKeyTyped

    private void jTextFieldCantidadEquipajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCantidadEquipajeKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarAeronave.doClick();
        }
    }//GEN-LAST:event_jTextFieldCantidadEquipajeKeyTyped

    private void jTextFieldCostoMantenimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostoMantenimientoKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarAeronave.doClick();
        }
    }//GEN-LAST:event_jTextFieldCostoMantenimientoKeyTyped

    private void jTextFieldCostoHangarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCostoHangarKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarAeronave.doClick();
        }
    }//GEN-LAST:event_jTextFieldCostoHangarKeyTyped

    private void jButtonModificarAeronaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonModificarAeronaveKeyTyped
        char teclaPresionada = evt.getKeyChar();
        if (teclaPresionada == KeyEvent.VK_ENTER) {
            jButtonModificarAeronave.doClick();
        }
    }//GEN-LAST:event_jButtonModificarAeronaveKeyTyped

    private void jButtonBuscarAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarAeronaveActionPerformed
        try {
            buscarParaModificar();
        } catch (java.lang.NullPointerException e1) {
            Icon imagenError = new ImageIcon(getClass().getResource("/iconos/baseline_warning_black_36dp.png"));
            JOptionPane.showMessageDialog(this, "La aeronave no existe", "Error al buscar la aeronave", JOptionPane.INFORMATION_MESSAGE,imagenError);
        }
    }//GEN-LAST:event_jButtonBuscarAeronaveActionPerformed

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        principal.volverAGestionAeronavePresidente(this);
    }//GEN-LAST:event_jButtonVolver1ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarAeronave;
    private javax.swing.JButton jButtonModificarAeronave;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelCantidadAsientos;
    private javax.swing.JLabel jLabelCantidadEquipajeSoporado;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelCostoMantenimiento;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelModelo;
    private javax.swing.JLabel jLabelTituloAregarAvion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextFieldCantidadAsientos;
    private javax.swing.JTextField jTextFieldCantidadEquipaje;
    private javax.swing.JTextField jTextFieldCostoHangar;
    private javax.swing.JTextField jTextFieldCostoMantenimiento;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables

    private void llenarCampos(Avion aviones) {
        String matricula = jTextFieldMatricula.getText();
        jTextFieldMarca.setText(principal.getControladorPilaAvion().buscarPorMatricula(matricula).getMarca());
        jTextFieldModelo.setText(principal.getControladorPilaAvion().buscarPorMatricula(matricula).getModelo());
        int cantidadAsientosINT = principal.getControladorPilaAvion().buscarPorMatricula(matricula).getNumeroAsientos();
        String cantidadAsientosString = Integer.toString(cantidadAsientosINT);
        jTextFieldCantidadAsientos.setText(cantidadAsientosString);
        Double cantidadEquipaje = principal.getControladorPilaAvion().buscarPorMatricula(matricula).getCantidadEquipajeSoportado();
        String cantidadEquipajeString = String.valueOf(cantidadEquipaje);
        jTextFieldCantidadEquipaje.setText(cantidadEquipajeString);
        Double costoMantenimiento = principal.getControladorPilaAvion().buscarPorMatricula(matricula).getCostoMantenimiento();
        String costoMantenimientoString = String.valueOf(costoMantenimiento);
        jTextFieldCostoMantenimiento.setText(costoMantenimientoString);
        Double costoHangar = principal.getControladorPilaAvion().buscarPorMatricula(matricula).getCostoHangar();
        String costoHangarString = String.valueOf(costoHangar);
        jTextFieldCostoHangar.setText(costoHangarString);
    }

    private void buscarParaModificar() {
        String matricula = jTextFieldMatricula.getText();
        Avion actual = principal.controladorPilaAvion.buscarPorMatricula(matricula);
        llenarCampos(actual);
    }

    private void borrar() {
        String matricula = jTextFieldMatricula.getText();
        principal.controladorPilaAvion.popAvion(matricula);
        System.out.println("Borra campos");
        System.out.println("");
        actualizarListaAviones();;
        System.out.println(principal.controladorPilaAvion.TotalAviones());
    }

    private void actualizarListaAviones() {
        String[] aviones = principal.controladorPilaAvion.darAviones();
    }

    private void agregar() {
        try {
            String nMatricula = jTextFieldMatricula.getText();
            String marca = jTextFieldMarca.getText();
            String modelo = jTextFieldModelo.getText();
            String cantidadAsientosString = jTextFieldCantidadAsientos.getText();
            int numeroAsientos = Integer.parseInt(cantidadAsientosString);
            String cantidadEquipajeString = jTextFieldCantidadEquipaje.getText();
            double cantidadEquipajeSoportado = Double.parseDouble(cantidadEquipajeString);
            String costoMantenimientoString = jTextFieldCostoMantenimiento.getText();
            double costoMantenimiento = Double.parseDouble(costoMantenimientoString);
            String costoHangarString = jTextFieldCostoHangar.getText();
            double costoHangar = Double.parseDouble(costoHangarString);
            Avion actual = new Avion(nMatricula, marca, modelo, numeroAsientos, cantidadEquipajeSoportado, costoMantenimiento, costoHangar);
            System.out.println(actual);
            boolean valor = principal.controladorPilaAvion.pushAvion(actual);
            System.out.println("cuantos" + principal.controladorPilaAvion.TotalAviones());
            if (valor == false) {
                JOptionPane.showMessageDialog(this, "El avion ya existe", "Agregar", JOptionPane.INFORMATION_MESSAGE);
            } else if (valor == true) {
                principal.controladorPilaAvion.pushAvion(actual);
                principal.volverAGestionAeronavePresidente(this);
            }
        } catch (java.lang.NumberFormatException e2) {
            JOptionPane.showMessageDialog(this, "Tiene un campo donde el valor no es valido o esta vacio", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
