package vista;

import AppPackage.AnimationClass;
import static java.awt.Frame.ICONIFIED;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Camilo y Roberth
 */
public class PresidenteJPanel extends javax.swing.JPanel {

    private Principal principal;

    /**
     * Creates new form GestionDePruebaPresidente
     */
    public PresidenteJPanel(Principal principal) {
        this.principal = principal;
        initComponents();
        moverALaDerecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCerrar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelAereoUSB = new javax.swing.JLabel();
        jButtonGestionAvion = new javax.swing.JButton();
        jButtonGestionVuelos = new javax.swing.JButton();
        jButtonGestionUsuario = new javax.swing.JButton();
        jSeparatorHorizontal = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonVolver1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_close_white_18dp.png"))); // NOI18N
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
        });
        add(jLabelCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_expand_more_white_18dp.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        jLabelAereoUSB.setFont(new java.awt.Font("Harlow Solid Italic", 1, 36)); // NOI18N
        jLabelAereoUSB.setText("AereoUSB");
        add(jLabelAereoUSB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 50));

        jButtonGestionAvion.setBackground(new java.awt.Color(0, 153, 204));
        jButtonGestionAvion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGestionAvion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_airplanemode_active_black_24dp.png"))); // NOI18N
        jButtonGestionAvion.setText("Gestion Aviones");
        jButtonGestionAvion.setBorderPainted(false);
        jButtonGestionAvion.setContentAreaFilled(false);
        jButtonGestionAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionAvionActionPerformed(evt);
            }
        });
        add(jButtonGestionAvion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, 40));

        jButtonGestionVuelos.setBackground(new java.awt.Color(0, 153, 204));
        jButtonGestionVuelos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGestionVuelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_flight_takeoff_black_24dp.png"))); // NOI18N
        jButtonGestionVuelos.setText("Gestion Vuelos");
        jButtonGestionVuelos.setContentAreaFilled(false);
        jButtonGestionVuelos.setDefaultCapable(false);
        jButtonGestionVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionVuelosActionPerformed(evt);
            }
        });
        add(jButtonGestionVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jButtonGestionUsuario.setBackground(new java.awt.Color(0, 153, 204));
        jButtonGestionUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGestionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_supervisor_account_black_24dp.png"))); // NOI18N
        jButtonGestionUsuario.setText("Gestion Usuarios");
        jButtonGestionUsuario.setBorderPainted(false);
        jButtonGestionUsuario.setContentAreaFilled(false);
        jButtonGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionUsuarioActionPerformed(evt);
            }
        });
        add(jButtonGestionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, 50));
        add(jSeparatorHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 482, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/isologoUSB_1.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, -90, 480, 510));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Bienvenido presidente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jButtonVolver1.setBackground(new java.awt.Color(144, 202, 249));
        jButtonVolver1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/baseline_chevron_left_black_24dp.png"))); // NOI18N
        jButtonVolver1.setBorder(null);
        jButtonVolver1.setContentAreaFilled(false);
        jButtonVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolver1ActionPerformed(evt);
            }
        });
        add(jButtonVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGestionAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionAvionActionPerformed
        GestionAeronaves();
    }//GEN-LAST:event_jButtonGestionAvionActionPerformed

    private void jButtonGestionVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionVuelosActionPerformed
        GestionVuelos();
    }//GEN-LAST:event_jButtonGestionVuelosActionPerformed

    private void jButtonGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionUsuarioActionPerformed
        GestionUsuarios();
    }//GEN-LAST:event_jButtonGestionUsuarioActionPerformed

    private void jButtonVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolver1ActionPerformed
        principal.volverAInicio(this);
    }//GEN-LAST:event_jButtonVolver1ActionPerformed

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(principal, "¿Desea salir de la plataforma?", "Salir", dialog);
        if (result == 0) {
            ((Principal) SwingUtilities.getWindowAncestor(this)).dispose();
        }
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        principal.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGestionAvion;
    private javax.swing.JButton jButtonGestionUsuario;
    private javax.swing.JButton jButtonGestionVuelos;
    private javax.swing.JButton jButtonVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAereoUSB;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JSeparator jSeparatorHorizontal;
    // End of variables declaration//GEN-END:variables

    private void GestionAeronaves() {
        principal.irAGestionAeronavesPresidente(this);
    }

    private void GestionUsuarios() {
        principal.irAGestionClientesPresidente(this);
    }

    private void GestionVuelos() {
        principal.irAGestionVuelosPresidente(this);
    }

    private void GestionTrabajador() {
        principal.irAGestionTrabajadoresPresidente(this);
    }

    private void moverALaDerecha() {
        //    ---->
        AnimationClass jButtonGestionAvionB = new AnimationClass();
        jButtonGestionAvionB.jButtonXRight(-150, 200, 10, 5, jButtonGestionAvion);
        AnimationClass jButtonGestionTrabajadorB = new AnimationClass();
        AnimationClass jButtonGestionUsuarioB = new AnimationClass();
        jButtonGestionUsuarioB.jButtonXRight(-150, 200, 10, 5, jButtonGestionUsuario);
        AnimationClass jButtonGestionVuelosB = new AnimationClass();
        jButtonGestionVuelosB.jButtonXRight(-150, 200, 10, 5, jButtonGestionVuelos);
    }
}
